import streamlit as st 
import pandas as pd
import matplotlib.pyplot as plt

from cleaner import clean_data
from analyzer import analyze_df


# page title
st.title("📊 Sales Analytics Dashboard")
st.caption("Interactive Business Intelligence & Revenue Insights Platform")

# load data 
df = pd.read_csv("data/sales.csv")

# clean data
cleaned_df = clean_data(df)

# sidebar filter 
st.sidebar.title("⚙️ Dashboard Filters")
selected_category = st.sidebar.selectbox(
    "Select Category",
    cleaned_df['category'].unique()
)
filtered_df = cleaned_df[cleaned_df['category'] == selected_category]

# analyze data
total_revenue, avg_revenue, top_products = analyze_df(filtered_df)

# KPIs
st.divider()
st.header("📈 Business KPIs")

col1,col2,col3 = st.columns(3)
with col1:
    st.metric(
        "💰Total Revenue",
        f"${total_revenue:,.2f}"
    )
with col2:
    st.metric(
        "📈Average Revenue",
        f"${avg_revenue:,.2f}"
    )
with col3:
    st.metric(
        "🏆Top Product",
        top_products
    )

# show filtered data
st.divider()
st.header("🧹Filtered Sales Data")
st.dataframe(filtered_df)

# Revenue by product chart 
st.divider()
st.header("📊 Revenue by Product")
st.write(
    "This chart shows revenue generated by each product category."
)

filtered_df['revenue'] =(
    filtered_df['quantity'] *
    filtered_df['price']
)

product_revenue = filtered_df.groupby('product')['revenue'].sum()
fig, ax = plt.subplots()
product_revenue.plot(
    kind='bar', 
    ax=ax
)

st.divider()

st.caption(
    "Built with Python, Streamlit, Pandas, SQLite & Matplotlib"
)
st.pyplot(fig)








